# -*- coding: utf-8 -*-
"""beatriz_prado_Aula10Prático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ED9QpRvBgXQ1jMjHzSGzO-IZMWPe-RXX
"""

import random

distancias = [
    [0, 2, 4, 6, 8],
    [2, 0, 3, 5, 7],
    [4, 3, 0, 2, 4],
    [6, 5, 2, 0, 3],
    [8, 7, 4, 3, 0]
]

volumes = [0, 2, 3, 4, 2]  # bairro 0 = depósito
capacidade = 5

NUM_BAIRROS = len(volumes)


# --------------------------
# GERAÇÃO DE INDIVÍDUO
# --------------------------

def gerar_individuo():
    bairros = list(range(1, NUM_BAIRROS))
    random.shuffle(bairros)

    individuo = []
    carga = 0

    for b in bairros:
        if carga + volumes[b] > capacidade:
            individuo.append(-1)
            carga = 0
        individuo.append(b)
        carga += volumes[b]

    return individuo


# --------------------------
# FITNESS
# --------------------------

def calcular_fitness(ind):
    total_dist = 0
    carga = 0
    penalidade = 0
    viagens = 1

    atual = 0  # começa no depósito

    for gene in ind:
        if gene == -1:
            total_dist += distancias[atual][0]
            atual = 0
            carga = 0
            viagens += 1
            continue

        total_dist += distancias[atual][gene]
        carga += volumes[gene]

        if carga > capacidade:
            penalidade += 1000 * (carga - capacidade)

        atual = gene

    total_dist += distancias[atual][0]

    penalidade += viagens * 50

    return total_dist + penalidade


# --------------------------
# SELEÇÃO (TORNEIO)
# --------------------------

def selecao(pop):
    a, b = random.sample(pop, 2)
    return a if calcular_fitness(a) < calcular_fitness(b) else b


# --------------------------
# CROSSOVER (simples)
# --------------------------

def crossover(pai1, pai2):
    corte = random.randint(1, len(pai1)-1)
    filho = pai1[:corte]

    for gene in pai2:
        if gene not in filho:
            filho.append(gene)

    return filho


# --------------------------
# MUTAÇÃO
# --------------------------

def mutacao(ind):
    i, j = random.sample(range(len(ind)), 2)
    ind[i], ind[j] = ind[j], ind[i]


# --------------------------
# ALGORITMO GENÉTICO
# --------------------------

def algoritmo_genetico():
    pop = [gerar_individuo() for _ in range(20)]

    for _ in range(100):
        nova_pop = []

        for _ in range(len(pop)):
            p1 = selecao(pop)
            p2 = selecao(pop)

            filho = crossover(p1, p2)

            if random.random() < 0.1:
                mutacao(filho)

            nova_pop.append(filho)

        pop = nova_pop

    melhor = min(pop, key=calcular_fitness)
    return melhor


# --------------------------
# EXECUÇÃO
# --------------------------

melhor = algoritmo_genetico()

print("Melhor solução:", melhor)
print("Fitness:", calcular_fitness(melhor))