# -*- coding: utf-8 -*-
"""beatriz_prado_aula5Prático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeaKknfROTKZCWVpiTgCktSSpme77B8-
"""

#código feito com auxilio da IA - ChatGPT, para aperfeiçoamento e correções de erro,
#além de sugestões de exibição para o usuário

from collections import deque
import copy
import time

tam = 4
mapa = [[" " for _ in range(tam)] for _ in range(tam)]

wumpus = (1, 2)
ouro = (0, 2)
abismos = [(3, 0), (2, 1), (0, 3)]

mapa[wumpus[0]][wumpus[1]] = "W"
mapa[ouro[0]][ouro[1]] = "O"

for a in abismos:
    mapa[a[0]][a[1]] = "P"

movimentos = [(-1, 0), (1, 0), (0, -1), (0, 1)]

def posicaoValida(x, y):
    return 0 <= x < tam and 0 <= y < tam

def mostrarMapa(atual=None, caminho=None):
    mapa_temp = copy.deepcopy(mapa)
    if caminho:
        for cx, cy in caminho:
            if mapa_temp[cx][cy] == " ":
                mapa_temp[cx][cy] = "."
    if atual:
        x, y = atual
        mapa_temp[x][y] = "A"
    for linha in mapa_temp:
        print(linha)

def bfsPassoAPAsso(inicio, objetivo):
    fila = deque()
    fila.append((inicio, [inicio]))
    visitados = set([inicio])
    passo = 0

    while fila:
        passo += 1
        (x, y), caminho = fila.popleft()
        print(f"\n ---- PASSO {passo} ---- ")
        print(f"Explorando: {(x, y)}")
        print(f"Caminho atual: {caminho}")
        mostrarMapa(atual=(x, y), caminho=caminho)
        time.sleep(0.5)

        if (x, y) == objetivo:
            print("\n OBJETIVO ENCONTRADO!")
            return caminho

        for dx, dy in movimentos:
            novo_x, novo_y = x + dx, y + dy
            if posicaoValida(novo_x, novo_y) and (novo_x, novo_y) not in visitados:
                if mapa[novo_x][novo_y] in ("P", "W"):
                    continue
                visitados.add((novo_x, novo_y))
                fila.append(((novo_x, novo_y), caminho + [(novo_x, novo_y)]))
    return None

def executaAgente():
    inicio = (0, 0)

    print(" ---- INICIANDO ---- ")
    mostrarMapa()

    print("\n ---- Buscando caminho até o ouro ---- ")
    caminhoOuro = bfsPassoAPAsso(inicio, ouro)

    if not caminhoOuro:
        print("\n Não foi possível encontrar o ouro ")
        return

    print("\nCAMINHO ATÉ O OURO ENCONTRADO!!!!!!!!!")
    print(caminhoOuro)

    print("\n ---- Buscando caminho de volta ---- ")
    caminhoVolta = bfsPassoAPAsso(ouro, inicio)

    if not caminhoVolta:
        print("\n Não foi possível voltar para o início ")
        return

    print("\nCAMINHO DE VOLTA ENCONTRADO!!!!!!!!!")
    print(caminhoVolta)

    print("\nMISSÃO CONCLUÍDA: agente pegou o ouro e retornou com sucesso!")

executaAgente()