# -*- coding: utf-8 -*-
"""beatriz_prado_Aula13Prático.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VC4GHu0GSfavJPy2z8e0C050HOfqWFz
"""

#bibliotecas utilizadas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)

df["target"] = wine.target
print(df.head())

#a) Boxplot, média, desvio padrão e outliers
print("\n---------- MÉDIA ----------")
print(df.describe().loc["mean"])

print("\n---------- DESVIO PADRÃO ----------")
print(df.describe().loc["std"])

plt.figure(figsize=(15,6))
sns.boxplot(data=df.drop("target", axis=1))
plt.title("Boxflot das Features Originais")
plt.xticks(rotation=90)
plt.show()

#b) normalização de dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.drop("target", axis=1))
df_scaled = pd.DataFrame(X_scaled, columns=wine.feature_names)

plt.figure(figsize=(15,6))
sns.boxplot(data=df_scaled)

plt.title("Boxplot normalizado")
plt.xticks(rotation=90)
plt.show()

#c) distruibção de classes
plt.figure(figsize=(6,4))
sns.countplot(x=df["target"])
plt.title("Distribuição das Classes")
plt.xlabel("Classe")
plt.ylabel("Quantidade")
plt.show()

#d) matriz de correlação
corr = df.drop("target", axis=1).corr()
plt.figure(figsize=(12,10))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlação")
plt.show()

corr_pairs = corr.unstack()

corr_pairs = corr_pairs[corr_pairs != 1]
sorted_corr = corr_pairs.abs().sort_values(ascending=False)

print("\n---------- MAIORES CORRELAÇÕES ----------")
print(sorted_corr.head(10))

#e) PCA 2D
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df_pca = pd.DataFrame()

df_pca["PCA1"] = X_pca[:,0]
df_pca["PCA2"] = X_pca[:,1]
df_pca["Classe"] = df["target"]

plt.figure(figsize=(8,6))
sns.scatterplot(data=df_pca, x="PCA1", y="PCA2", hue="Classe", palette="Set1", s=100)
plt.title("PCA 2D - Wine Dataset")
plt.show()