# -*- coding: utf-8 -*-
"""beatriz_prado_aula9Pratico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkGAM1TKn1BAuf0YZUBfpl0i1OCvMLzw
"""

#código feito com auxilio da IA - ChatGPT, para aperfeiçoamento e correções de erro,

from collections import deque

# Verifica se o estado é válido
def valido(m, c):
  m_dir = 3 - m #compara a qntd de um lado com o outro
  c_dir = 3 - c

  #evita estados impossíveis
  if m < 0 or c < 0 or m > 3 or c > 3:
    return False

    #garante que não vai ter mais canibais do que missionários
  if (m > 0 and c > m) or (m_dir > 0 and c_dir > m_dir):
    return False

  return True #apenas se passou por todos os testes


def bfs():
  #(M, C, Barco)
  inicial = (3, 3, 0) #inicia com todas as pessoas na esquerda
  objetivo = (0, 0, 1) #objetivo é nao ter ninguem na esquerda

  fila = deque()
  fila.append(inicial)

  visitado = set()
  visitado.add(inicial)

  # para reconstruir o caminho
  pai = {inicial: None} #guarda de onde cada estado veio

  # possíveis movimentos no barco
  movimentos = [
      (1, 0),  # 1 M
      (2, 0),  # 2 M
      (0, 1),  # 1 C
      (0, 2),  # 2 C
      (1, 1)   # 1 M + 1 C
    ]

  while fila:
    atual = fila.popleft() #pega o primeiro da fila para a busca em largura

    if atual == objetivo: #se chegou no objetivo, achou a solução, então reconstroi o caminho
      return reconstruir_caminho(pai, atual)

    m, c, barco = atual

    for dm, dc in movimentos: #verifica todos os movimentos possíveis
      if barco == 0:  # indo pra direita
        novo = (m - dm, c - dc, 1) #remove pessoas da esquerda
      else:  # voltando pra esquerda
        novo = (m + dm, c + dc, 0) #adiciona pessoas na esquerda

      if valido(novo[0], novo[1]) and novo not in visitado: #aceita o estado apenas se for válido e não foi visitado ainda
        visitado.add(novo) #marca como visitado
        fila.append(novo) #coloca na fila
        pai[novo] = atual #registra de onde veio esse estado (para construir o caminho)

  return None #caso não exista solução


def reconstruir_caminho(pai, estado):
    caminho = []
    while estado is not None: #parte do objetivo até o estado inicial
        caminho.append(estado)
        estado = pai[estado] #a partir dos pais
    return caminho[::-1] #retorna o caminho inicio -> objetivo


def imprimir_solucao(caminho):
    for estado in caminho:
        m, c, barco = estado
        lado = "Esquerda" if barco == 0 else "Direita"
        print(f"M={m}, C={c}, Barco: {lado}")


# Executa
solucao = bfs()

if solucao:
    print("Solução encontrada:\n")
    imprimir_solucao(solucao)
else:
    print("Sem solução.")