# -*- coding: utf-8 -*-
"""beatriz_prado_Aula15Prático

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDJSzlrWC0iYS_XgNLIL5ECJsQA7zsp5
"""

# Bibliotecas
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import accuracy_score

wine = load_wine()

X = wine.data
Y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#SVM
svm = SVC(kernel='linear', C=1)
#define que o SVM utilizará um hiperplano linear para separar as classes e controla o equilíbrio
#entre maximizar a margem e reduzir erros de classificação.

svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

acc_svm = accuracy_score(y_test, y_pred_svm)

print("========== SVM ==========")
print("Acurácia:", acc_svm)
print("Número de acertos:", (y_pred_svm == y_test).sum())
print()

#Perceptron
perceptron = Perceptron(
    eta0=0.1, #Taxa de aprendizado do modelo
    max_iter=1000, #Número máximo de épocas de treinamento
    random_state=42 #Define uma semente fixa para reproduzir os mesmos resultados
)

perceptron.fit(X_train, y_train)

y_pred_perc = perceptron.predict(X_test)

acc_perc = accuracy_score(y_test, y_pred_perc)

print("========== PERCEPTRON ==========")
print("Acurácia:", acc_perc)
print("Número de acertos:", (y_pred_perc == y_test).sum())
print()

# MLP
mlp = MLPClassifier(
    hidden_layer_sizes=(10,), #Define uma camada oculta com 10 neurônios
    activation='relu', #Função de ativação utilizada na rede neural
    learning_rate_init=0.001, #Taxa de aprendizado inicial
    max_iter=2000, #Número máximo de iterações do treinamento
    random_state=42 #Mantém os resultados reproduzíveis
)

mlp.fit(X_train, y_train)

y_pred_mlp = mlp.predict(X_test)

acc_mlp = accuracy_score(y_test, y_pred_mlp)

print("========== MLP ==========")
print("Acurácia:", acc_mlp)
print("Número de acertos:", (y_pred_mlp == y_test).sum())