# -*- coding: utf-8 -*-
"""beatriz_prado_Aula19Prático

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rm5HmduMOIGFCZ_mqghq16_rZEggM0w7
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

# 1. Carregar e preparar o dataset CIFAR-10
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalizar os valores dos pixels para ficarem entre 0 e 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Nomes das classes do dataset para fins de visualização
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

# 2. Construir a Base Convolucional
model = models.Sequential()

# Primeira camada convolucional + Max Pooling
# O input_shape é (32, 32, 3) porque as imagens são 32x32 pixels com 3 canais de cor (RGB)
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))

# Segunda camada convolucional + Max Pooling
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

# Terceira camada convolucional
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

# 3. Adicionar camadas Densas (Cabeça de Classificação)
# Achata (Flatten) os mapas de características 3D para vetores 1D antes de passar para a camada Dense
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10)) # 10 saídas (uma para cada classe)

# Exibir a arquitetura completa do modelo no console
model.summary()

# 4. Compilar o modelo
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# 5. Treinar o modelo
# Treinaremos por 10 épocas para validação rápida, assim como no tutorial original
history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

# 6. Avaliar a precisão final do modelo nos dados de teste
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)
print(f"\nPrecisão nos dados de teste (Acurácia): {test_acc:.4f}")

# 7. Plotar os gráficos de evolução do treinamento
plt.figure(figsize=(8, 5))
plt.plot(history.history['accuracy'], label='Acurácia de Treino')
plt.plot(history.history['val_accuracy'], label = 'Acurácia de Validação')
plt.xlabel('Época')
plt.ylabel('Acurácia')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')
plt.title('Evolução do Treinamento da CNN')
plt.show()