# -*- coding: utf-8 -*-
"""beatriz_prado_Aula14Prático

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DVZkFwgjc1sbVmno6Ia4Q_ntuQtTVae
"""

# Bibliotecas
import pandas as pd

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

wine = load_wine()
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#KNN
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

acc_knn = accuracy_score(y_test, y_pred_knn)

print("========== KNN ==========")
print("Acurácia:", acc_knn)
print("Número de acertos:", (y_pred_knn == y_test).sum())
print()

# NAIVE BAYES
nb = GaussianNB()

nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

acc_nb = accuracy_score(y_test, y_pred_nb)

print("========== NAIVE BAYES ==========")
print("Acurácia:", acc_nb)
print("Número de acertos:", (y_pred_nb == y_test).sum())
print()

#Árvore de Decisão
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

acc_dt = accuracy_score(y_test, y_pred_dt)

print("========== ÁRVORE DE DECISÃO ==========")
print("Acurácia:", acc_dt)
print("Número de acertos:", (y_pred_dt == y_test).sum())