# -*- coding: utf-8 -*-
"""beatriz_prado_aula3Prático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVix25Zc0fq_FoBLrqkip5E10tbJzVUl

## 1. Normalização Min-Max 📊
Na preparação de dados para Redes Neurais, é muito comum precisarmos colocar todas as variáveis numéricas na mesma escala (geralmente entre 0 e 1). A fórmula da Normalização Min-Max é:
$$X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

**Tarefa:** Crie um programa que faça a leitura (via teclado) de cinco valores. Calcule e exiba o valor normalizado de cada um deles.
"""

valores = []

for i in range(5):
  valor = float(input(f"Digite um valor {i+1}: "))
  valores.append(valor)

x_min = valores[0]
x_max = valores[0]

for v in valores:
  if v < x_min:
    x_min = v
  if v > x_max:
    x_max = v

print('\n------Valores normalizados------')
for i in range(5):
  xnorm = (valores[i]-x_min)/ (x_max-x_min)
  print(f"Valor {i+1} normalizado: {xnorm:.2f}")

"""## 2. A Matriz de Confusão 🎲
Vamos avaliar um classificador binário gerado aleatoriamente!
1. Importe o módulo `random`.
2. Construa duas listas de 20 posições cada: `y_real` e `y_predito`. Preencha-as com números binários aleatórios (0 ou 1) usando `random.randint(0, 1)`.

**Tarefa:** Crie um dicionário para rastrear a matriz de confusão desse classificador.

**Matriz de Confusão:**
| | Real 0 | Real 1 |
| :--- | :--- | :--- |
| **Predito 0** | VN | FP |
| **Predito 1** | FN | VP |

"""

import random
y_real = []
y_predito = []

for i in range(20):
  y_real.append(random.randint(0, 1))
  y_predito.append(random.randint(0, 1))

matriz_confusao = {
   "VN": 0,
   "FP": 0,
   "FN": 0,
   "VP": 0,
}

for i in range(20):
  real = y_real[i]
  predito = y_predito[i]

  if real == 0 and predito == 0:
    matriz_confusao["VN"] += 1
  elif real == 0 and predito == 1:
    matriz_confusao["FN"] += 1
  elif real == 1 and predito == 0:
    matriz_confusao["FP"] += 1
  elif real == 1 and predito == 1:
    matriz_confusao["VP"] += 1

print("y_real:", y_real)
print("y_predito:", y_predito)
print('\n------Matriz de confusão------')
print(matriz_confusao)

"""## 3. Métricas Customizadas e Docstrings 📏
Usando o dicionário da Matriz de Confusão gerado no exercício anterior, vamos calcular o **F1-Score**.

O F1-Score é a média harmônica entre a *Precisão* e o *Recall*:
- **Precisão:** $\frac{VP}{VP + FP}$ (Dos que o modelo disse ser 1, quantos eram 1 de verdade?)
- **Recall:** $\frac{VP}{VP + FN}$ (Dos que eram realmente 1, quantos o modelo identificou?)
- **F1-Score:** $2 \times \frac{Precisão \times Recall}{Precisão + Recall}$

**Tarefa:**
1. Crie uma função chamada `calcular_f1_score(matriz_confusao: dict) -> float`.
2. Escreva uma **Docstring** completa para a função, descrevendo seu argumento e retorno.
3. Dentro da função, extraia os valores (VP, FP e FN) do dicionário recebido. Calcule a Precisão, o Recall e finalmente o F1-Score, retornando o valor final. *(Dica: Trate o caso de divisão por zero retornando 0.0 caso ocorra)*.
4. Ao final, chame a sua função passando o dicionário do Exercício 2 e exiba o resultado no console com 4 casas decimais.

"""

def calcular_f1_score(matriz_confusao: dict) -> float:
  VP = matriz_confusao["VP"]
  FP = matriz_confusao["FP"]
  FN = matriz_confusao["FN"]

  #calculo da precisão
  if VP + FP == 0:
    precisao = 0.0
  else:
    precisao = VP / (VP + FP)

  #calculo de recall
  if VP + FN == 0:
    recall = 0.0
  else:
    recall = VP / (VP + FN)

  #calculo F1-Score
  if precisao + recall == 0:
    return 0.0
  else:
    f1_score = 2 * (precisao * recall) / (precisao + recall)
    return f1_score



f1 = calcular_f1_score(matriz_confusao)
print(f"F1-Score: {f1:.4f}")

"""## 4. Árvore Binária de Busca 🌳
**Tarefa:** Crie uma classe `NoArvore`. Ela deve receber no método construtor `__init__` um valor inteiro e inicializar as referências `esquerda` e `direita`. Crie dois métodos para essa classe:
- `inserir(self, valor: int)`: Se o valor for menor que o do nó atual, desce para a esquerda (se estiver livre, aloca um nó novo, se não, chama a inserção recursiva à esquerda). Faz o espelho para a direita.
- `buscar(self, valor: int) -> bool`: Retorna `True` se o valor existir na árvore sob esse nó, e `False` caso contrário, usando a lógica clássica da BST.

"""

class NoArvore:
  def __init__(self, valor:int):
    self.valor = valor
    self.esquerda = None
    self.direita = None


  def inserir(self, valor:int):
    if valor < self.valor:
      if self.esquerda is None:
        self.esquerda = NoArvore(valor)
      else:
        self.esquerda.inserir(valor)
    else:
      if self.direita is None:
        self.direita = NoArvore(valor)
      else:
        self.direita.inserir(valor)


  def buscar(self, valor:int)->bool:
    if valor == self.valor:
      return True
    elif valor < self.valor:
      if self.esquerda is None:
        return False
      else:
        return self.esquerda.buscar(valor)
    else:
      if self.direita is None:
        return False
      else:
        return self.direita.buscar(valor)


# Exemplo: Criando a árvore com raiz 10
raiz = NoArvore(10)

# Inserindo valores
raiz.inserir(5)
raiz.inserir(15)
raiz.inserir(3)
raiz.inserir(7)
raiz.inserir(12)
raiz.inserir(18)

# Buscando valores
print(raiz.buscar(7))   # True
print(raiz.buscar(6))   # False
print(raiz.buscar(15))  # True