# -*- coding: utf-8 -*-
"""MundoWumpus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqmHat7wgPvWUNo4x4gWzSHGn3zVoUyR
"""

# código feito com auxílio de IA
import random

TAMANHO = 4

mapa = [[" " for _ in range(TAMANHO)] for _ in range(TAMANHO)] # mapa vazio
jogador = [0,0]  # [0,0] representa [1,1]

# elementos do jogo no mapa
wumpus = (1,2)
ouro = (2,3)
abismos = [(3,0), (2,1), (0,3)]

mapa[wumpus[0]][wumpus[1]] = "W"
mapa[ouro[0]][ouro[1]] = "O"
for a in abismos:
    mapa[a[0]][a[1]] = "P"

# início do jogo
flecha = True
pontos = 0
tem_ouro = False

def adjacentes(posicao):
    x, y = posicao
    return [(x+1, y), (x-1, y), (x, y+1), (x, y-1)]

def percepcao(posicao):
    x, y = posicao
    percepcoes = []

    for adj in adjacentes(posicao):
        ax, ay = adj
        if 0 <= ax < TAMANHO and 0 <= ay < TAMANHO:
            if mapa[ax][ay] == "W":
                percepcoes.append("fedor")
            if mapa[ax][ay] == "P":
                percepcoes.append("brisa")

    if mapa[x][y] == "O":
        percepcoes.append("brilho")

    return percepcoes

# jogo
while True:
    p = percepcao(jogador)

    if p:
        print(f"\nVocê está na posição {[jogador[0]+1, jogador[1]+1]} e percebe {p}")
    else:
        print(f"\nVocê está na posição {[jogador[0]+1, jogador[1]+1]} e não percebe nada.")

    mov = input("Digite o movimento (cima, baixo, esquerda, direita, atirar, pegar): ")
    x, y = jogador

    # movimentação
    if mov == "cima":
        x -= 1
    elif mov == "baixo":
        x += 1
    elif mov == "esquerda":
        y -= 1
    elif mov == "direita":
        y += 1

    # pegar ouro
    elif mov == "pegar":
        if mapa[jogador[0]][jogador[1]] == "O":
            print("Você pegou o ouro!")
            pontos += 50
            mapa[jogador[0]][jogador[1]] = " "
            tem_ouro = True
        else:
            print("Não há ouro aqui.")
        continue

    # atirar flecha
    elif mov == "atirar":
        if flecha:
            flecha = False
            acertou = False

            for adj in adjacentes(jogador):
                ax, ay = adj
                if (ax, ay) == wumpus:
                    print("Você matou o Wumpus!")
                    pontos += 50
                    mapa[ax][ay] = " "
                    acertou = True

            if not acertou:
                print("Você errou o tiro!")
        else:
            print("Você não tem mais flechas!")
        continue

    # parede
    if x < 0 or x >= TAMANHO or y < 0 or y >= TAMANHO:
        print("Você bateu na parede!")
        continue

    jogador = [x, y]
    pontos -= 1

    # morte
    if mapa[x][y] == "W":
        print("Você foi devorado pelo Wumpus!")
        pontos -= 100
        break

    if mapa[x][y] == "P":
        print("Você caiu em um abismo!")
        pontos -= 100
        break

    # vitória (voltou para [1,1] com ouro)
    if jogador == [0,0] and tem_ouro:
        print("Você voltou para a posição [1,1] e escapou com o ouro!")
        pontos += 50
        break

print("Pontuação final:", pontos)